### ISSUE TITLE
Bot crashes when one of his relayed messages is deleted

### ISSUE THREAD

**Issue by LeonSkills** [LeonSkills/CoreHunting#13]
Can probably use something like
discord.on_message_delete(message):
\# check her if deleted message is relayed message

to fix it
[Docs here](
http://discordpy.readthedocs.io/en/latest/api.html#discord.on_message_delete)

**Comment by Wea1thRS** [comment]
fixed in #9f6da8ab71eb24b1a9b3400c55271ae996c20fdf
