### ISSUE TITLE
add an option to worlds named party

### ISSUE THREAD

**Issue by EefTop** [LeonSkills/CoreHunting#31]
add bit field to world to set it as a party world
w66(Cres) PARTY!!
is what i suggest order doesnt have to change tbh
?party 66
?rip 66
staff only
make it last for 60 min and when a core is called on a party world don't set time to 2:15 again but ignore it. (can still show core i guess)

**Comment by Wea1thRS** [comment]
fixed in 2d9ca36e7cb474f544fc03572ee5314c9b271d40
